#!/bin/bash

LOAD="$(mpstat 1 1 | awk '/Average/{print 100-$NF}')"
LOADI="$(echo $LOAD | cut -d'.' -f1)"

echo "$LOAD%"
echo "$LOADI%"

if [ "$LOADI" -ge 80 ]; then
	echo "#FF0000"
elif [ "$LOADI" -ge 50 ]; then
	echo "#FFFF00"
else
	echo "#FFFFFF"
fi
